# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idProveedores', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoP', models.CharField(max_length=30)),
                ('apellidoM', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
            ],
        ),
    ]
