# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('idNegocio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('domicilio', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('idProveedores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Proveedores')),
            ],
        ),
    ]
