# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_negocios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('idHorario', models.IntegerField(primary_key=True, serialize=False)),
                ('lunes', models.BooleanField(default=True)),
                ('horaLunes', models.TimeField()),
                ('martes', models.BooleanField(default=False)),
                ('horaMartes', models.TimeField()),
                ('miercoles', models.BooleanField(default=False)),
                ('horaMiercoles', models.TimeField()),
                ('jueves', models.BooleanField(default=False)),
                ('horaJueves', models.TimeField()),
                ('viernes', models.BooleanField(default=False)),
                ('horaViernes', models.TimeField()),
                ('sabado', models.BooleanField(default=False)),
                ('horaSabado', models.TimeField()),
                ('idNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Negocios')),
            ],
        ),
    ]
