# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('idTrabajador', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidoP', models.CharField(max_length=30)),
                ('apellidoM', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=2)),
                ('telefono', models.CharField(max_length=10)),
                ('licencia', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
