# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_trabajadores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camiones',
            fields=[
                ('idCamion', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('anio', models.CharField(max_length=4)),
                ('idTrabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Trabajadores')),
            ],
        ),
    ]
