# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_camiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('idMaterial', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialRecolectado',
            fields=[
                ('idMaterialRecolectado', models.IntegerField(primary_key=True, serialize=False)),
                ('peso', models.FloatField(max_length=7)),
                ('fecha', models.DateField()),
                ('idCamion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Camiones')),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Materiales')),
                ('idNegocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Negocios')),
            ],
        ),
    ]
